// lib/services/storage_service.dart

import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

import '../models/api_config.dart';
import '../models/chat_message.dart';
import '../models/code_snippet.dart';
import '../models/file_item.dart';
import '../models/project.dart';

/// Exception for storage operations.
class StorageException implements Exception {
  final String message;
  final String? operation;
  final dynamic originalError;

  const StorageException({
    required this.message,
    this.operation,
    this.originalError,
  });

  @override
  String toString() => 'StorageException [$operation]: $message';
}

/// Service for local data persistence using Hive.
///
/// Manages local storage for:
/// - Projects metadata
/// - Code snippets
/// - API configurations
/// - User settings/preferences
/// - Chat message history
///
/// Hive boxes are opened on [init] and remain open for the app lifecycle.
/// Call [dispose] to close all boxes when the app shuts down.
///
/// ```dart
/// final storage = StorageService();
/// await storage.init();
/// final projects = await storage.getProjects();
/// ```
class StorageService {
  /// Box names (must be unique).
  static const String _projectsBox = 'projects';
  static const String _snippetsBox = 'snippets';
  static const String _apiConfigsBox = 'api_configs';
  static const String _settingsBox = 'settings';
  static const String _chatHistoryBox = 'chat_history';
  static const String _filesBox = 'files';

  /// Internal cache of open Hive boxes.
  final Map<String, Box<dynamic>> _boxes = {};

  /// Whether the service has been initialized.
  bool _initialized = false;
  bool get isInitialized => _initialized;

  /// Creates a [StorageService]. Call [init] before use.
  StorageService();

  // ─── Initialization ────────────────────────────────────────────────

  /// Initialize Hive and open all required boxes.
  ///
  /// Must be called before any CRUD operations. Safe to call multiple
  /// times — subsequent calls are no-ops if already initialized.
  Future<void> init() async {
    if (_initialized) return;

    try {
      // Initialize Hive with app documents directory.
      if (!kIsWeb) {
        final dir = await getApplicationDocumentsDirectory();
        final hivePath = '${dir.path}/mobile_agent/hive';
        await Directory(hivePath).create(recursive: true);
        Hive.init(hivePath);
      }

      // Register all type adapters.
      _registerAdapters();

      // Open all boxes.
      await Future.wait([
        _openBox<Project>(_projectsBox),
        _openBox<CodeSnippet>(_snippetsBox),
        _openBox<ApiConfig>(_apiConfigsBox),
        _openBox<dynamic>(_settingsBox), // Dynamic: settings can be any type.
        _openBox<ChatMessage>(_chatHistoryBox),
        _openBox<FileItem>(_filesBox),
      ]);

      _initialized = true;
      debugPrint('[StorageService] Initialized successfully');
    } catch (e) {
      throw StorageException(
        message: 'Failed to initialize storage: $e',
        operation: 'init',
        originalError: e,
      );
    }
  }

  /// Register all Hive type adapters.
  ///
  /// Called during [init]. Each model class has a corresponding
  /// generated adapter (e.g., [ApiConfigAdapter]).
  void _registerAdapters() {
    // These adapters are generated by build_runner.
    // Run: dart run build_runner build
    if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(ApiConfigAdapter());
    if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(ChatMessageAdapter());
    if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(ProjectAdapter());
    if (!Hive.isAdapterRegistered(4)) Hive.registerAdapter(FileItemAdapter());
    if (!Hive.isAdapterRegistered(5)) Hive.registerAdapter(CodeSnippetAdapter());
    if (!Hive.isAdapterRegistered(10)) Hive.registerAdapter(MessageRoleAdapter());
    if (!Hive.isAdapterRegistered(11)) Hive.registerAdapter(FileItemTypeAdapter());
  }

  /// Open a Hive box with error handling.
  Future<void> _openBox<T>(String name) async {
    try {
      final box = await Hive.openBox<T>(name);
      _boxes[name] = box;
      debugPrint('[StorageService] Opened box: $name (${box.length} items)');
    } catch (e) {
      // If box is corrupted, delete and recreate.
      debugPrint('[StorageService] Failed to open box $name, attempting recovery: $e');
      await Hive.deleteBoxFromDisk(name);
      final box = await Hive.openBox<T>(name);
      _boxes[name] = box;
    }
  }

  /// Get an open box by name.
  Box<T> _getBox<T>(String name) {
    _ensureInitialized();
    final box = _boxes[name];
    if (box == null || !box.isOpen) {
      throw StorageException(
        message: 'Box "$name" is not open',
        operation: '_getBox',
      );
    }
    return box as Box<T>;
  }

  void _ensureInitialized() {
    if (!_initialized) {
      throw const StorageException(
        message: 'StorageService not initialized. Call init() first.',
        operation: '_ensureInitialized',
      );
    }
  }

  // ─── Projects CRUD ─────────────────────────────────────────────────

  /// Get all stored projects.
  ///
  /// Returns projects sorted by updatedAt (most recent first).
  /// Favorited projects appear at the top.
  Future<List<Project>> getProjects() async {
    final box = _getBox<Project>(_projectsBox);
    final projects = box.values.toList();

    projects.sort((a, b) {
      // Favorites first.
      if (a.isFavorite && !b.isFavorite) return -1;
      if (!a.isFavorite && b.isFavorite) return 1;
      // Then by updatedAt descending.
      return b.updatedAt.compareTo(a.updatedAt);
    });

    return projects;
  }

  /// Get a single project by ID.
  Future<Project?> getProject(String id) async {
    final box = _getBox<Project>(_projectsBox);
    return box.get(id);
  }

  /// Save (create or update) a project.
  Future<void> saveProject(Project project) async {
    try {
      final box = _getBox<Project>(_projectsBox);
      project.touch();
      await box.put(project.id, project);
      debugPrint('[StorageService] Saved project: ${project.name} (${project.id})');
    } catch (e) {
      throw StorageException(
        message: 'Failed to save project: $e',
        operation: 'saveProject',
        originalError: e,
      );
    }
  }

  /// Delete a project by ID.
  Future<void> deleteProject(String id) async {
    try {
      final box = _getBox<Project>(_projectsBox);
      await box.delete(id);
      debugPrint('[StorageService] Deleted project: $id');
    } catch (e) {
      throw StorageException(
        message: 'Failed to delete project: $e',
        operation: 'deleteProject',
        originalError: e,
      );
    }
  }

  /// Delete all projects (use with caution).
  Future<void> clearProjects() async {
    final box = _getBox<Project>(_projectsBox);
    await box.clear();
    debugPrint('[StorageService] Cleared all projects');
  }

  // ─── Snippets CRUD ─────────────────────────────────────────────────

  /// Get all stored code snippets.
  ///
  /// Returns snippets sorted by updatedAt (most recent first).
  /// Favorited snippets appear at the top.
  Future<List<CodeSnippet>> getSnippets() async {
    final box = _getBox<CodeSnippet>(_snippetsBox);
    final snippets = box.values.toList();

    snippets.sort((a, b) {
      if (a.isFavorite && !b.isFavorite) return -1;
      if (!a.isFavorite && b.isFavorite) return 1;
      return b.updatedAt.compareTo(a.updatedAt);
    });

    return snippets;
  }

  /// Get a single snippet by ID.
  Future<CodeSnippet?> getSnippet(String id) async {
    final box = _getBox<CodeSnippet>(_snippetsBox);
    return box.get(id);
  }

  /// Search snippets by query string.
  ///
  /// Searches in title, code, description, and tags.
  Future<List<CodeSnippet>> searchSnippets(String query) async {
    final lowerQuery = query.toLowerCase();
    final allSnippets = await getSnippets();

    return allSnippets.where((s) {
      return s.title.toLowerCase().contains(lowerQuery) ||
          s.code.toLowerCase().contains(lowerQuery) ||
          s.language.toLowerCase().contains(lowerQuery) ||
          (s.description?.toLowerCase().contains(lowerQuery) ?? false) ||
          s.tags.any((tag) => tag.toLowerCase().contains(lowerQuery));
    }).toList();
  }

  /// Get snippets filtered by tag.
  Future<List<CodeSnippet>> getSnippetsByTag(String tag) async {
    final allSnippets = await getSnippets();
    return allSnippets.where((s) => s.tags.contains(tag)).toList();
  }

  /// Get all unique tags across all snippets.
  Future<List<String>> getAllSnippetTags() async {
    final snippets = await getSnippets();
    final tags = <String>{};
    for (final s in snippets) {
      tags.addAll(s.tags);
    }
    return tags.toList()..sort();
  }

  /// Save (create or update) a snippet.
  Future<void> saveSnippet(CodeSnippet snippet) async {
    try {
      final box = _getBox<CodeSnippet>(_snippetsBox);
      snippet.touch();
      await box.put(snippet.id, snippet);
      debugPrint('[StorageService] Saved snippet: ${snippet.title} (${snippet.id})');
    } catch (e) {
      throw StorageException(
        message: 'Failed to save snippet: $e',
        operation: 'saveSnippet',
        originalError: e,
      );
    }
  }

  /// Delete a snippet by ID.
  Future<void> deleteSnippet(String id) async {
    try {
      final box = _getBox<CodeSnippet>(_snippetsBox);
      await box.delete(id);
      debugPrint('[StorageService] Deleted snippet: $id');
    } catch (e) {
      throw StorageException(
        message: 'Failed to delete snippet: $e',
        operation: 'deleteSnippet',
        originalError: e,
      );
    }
  }

  /// Delete all snippets.
  Future<void> clearSnippets() async {
    final box = _getBox<CodeSnippet>(_snippetsBox);
    await box.clear();
  }

  // ─── API Configs CRUD ──────────────────────────────────────────────

  /// Get all stored API configurations.
  Future<List<ApiConfig>> getApiConfigs() async {
    final box = _getBox<ApiConfig>(_apiConfigsBox);
    return box.values.toList();
  }

  /// Get the active (selected) API configuration.
  ///
  /// Returns the first config marked as active, or the first config
  /// if none are marked active. Returns null if no configs exist.
  Future<ApiConfig?> getActiveApiConfig() async {
    final configs = await getApiConfigs();
    if (configs.isEmpty) return null;

    try {
      return configs.firstWhere((c) => c.isActive);
    } catch (_) {
      return configs.first;
    }
  }

  /// Save (create or update) an API configuration.
  ///
  /// If [setAsActive] is true, deactivates all other configs first.
  Future<void> saveApiConfig(ApiConfig config, {bool setAsActive = false}) async {
    try {
      final box = _getBox<ApiConfig>(_apiConfigsBox);

      if (setAsActive) {
        // Deactivate all other configs.
        for (final existing in box.values) {
          if (existing.id != config.id && existing.isActive) {
            existing.isActive = false;
            await existing.save();
          }
        }
        config.isActive = true;
      }

      await box.put(config.id, config);
      debugPrint('[StorageService] Saved API config: ${config.name} (${config.id})');
    } catch (e) {
      throw StorageException(
        message: 'Failed to save API config: $e',
        operation: 'saveApiConfig',
        originalError: e,
      );
    }
  }

  /// Delete an API configuration.
  Future<void> deleteApiConfig(String id) async {
    try {
      final box = _getBox<ApiConfig>(_apiConfigsBox);
      await box.delete(id);
      debugPrint('[StorageService] Deleted API config: $id');
    } catch (e) {
      throw StorageException(
        message: 'Failed to delete API config: $e',
        operation: 'deleteApiConfig',
        originalError: e,
      );
    }
  }

  /// Set a specific config as the active one.
  Future<void> setActiveApiConfig(String id) async {
    final box = _getBox<ApiConfig>(_apiConfigsBox);

    for (final config in box.values) {
      config.isActive = config.id == id;
      await config.save();
    }
  }

  // ─── Settings / Preferences ────────────────────────────────────────

  /// Get a setting value by key.
  ///
  /// [T] must match the type that was stored. Common types:
  /// - String
  /// - int
  /// - double
  /// - bool
  /// - List<String>
  ///
  /// Returns null if the key does not exist.
  Future<T?> getSetting<T>(String key) async {
    final box = _getBox<dynamic>(_settingsBox);
    final value = box.get(key);
    if (value == null) return null;
    if (value is T) return value as T;
    // Handle type mismatches gracefully.
    debugPrint('[StorageService] Type mismatch for setting "$key": expected $T, got ${value.runtimeType}');
    return null;
  }

  /// Get a setting with a default value.
  ///
  /// Returns [defaultValue] if the key does not exist or type mismatches.
  Future<T> getSettingWithDefault<T>(String key, T defaultValue) async {
    final value = await getSetting<T>(key);
    return value ?? defaultValue;
  }

  /// Set a setting value.
  ///
  /// Overwrites any existing value for the key.
  Future<void> setSetting<T>(String key, T value) async {
    try {
      final box = _getBox<dynamic>(_settingsBox);
      await box.put(key, value);
      debugPrint('[StorageService] Set setting: $key = $value');
    } catch (e) {
      throw StorageException(
        message: 'Failed to set setting "$key": $e',
        operation: 'setSetting',
        originalError: e,
      );
    }
  }

  /// Remove a setting.
  Future<void> removeSetting(String key) async {
    final box = _getBox<dynamic>(_settingsBox);
    await box.delete(key);
  }

  /// Check if a setting exists.
  Future<bool> hasSetting(String key) async {
    final box = _getBox<dynamic>(_settingsBox);
    return box.containsKey(key);
  }

  // ─── Chat Message History ──────────────────────────────────────────

  /// Get all chat messages for a session.
  ///
  /// [sessionId] identifies the chat session (e.g., project ID or timestamp).
  /// Messages are returned in chronological order.
  Future<List<ChatMessage>> getChatMessages(String sessionId) async {
    final box = _getBox<ChatMessage>(_chatHistoryBox);
    final prefix = '${sessionId}_';

    final messages = box.values
        .where((msg) => msg.id.startsWith(prefix) || _getMessageSessionId(msg.id) == sessionId)
        .toList();

    // Sort by timestamp.
    messages.sort((a, b) => a.timestamp.compareTo(b.timestamp));
    return messages;
  }

  /// Save a chat message.
  ///
  /// [sessionId] groups messages together.
  Future<void> saveChatMessage(String sessionId, ChatMessage message) async {
    final box = _getBox<ChatMessage>(_chatHistoryBox);
    await box.put('${sessionId}_${message.id}', message);
  }

  /// Delete all messages for a session.
  Future<void> clearChatHistory(String sessionId) async {
    final box = _getBox<ChatMessage>(_chatHistoryBox);
    final keysToDelete = box.keys.where((key) {
      return key.toString().startsWith('${sessionId}_');
    }).toList();

    await box.deleteAll(keysToDelete);
    debugPrint('[StorageService] Cleared chat history for session: $sessionId');
  }

  /// Delete all chat history across all sessions.
  Future<void> clearAllChatHistory() async {
    final box = _getBox<ChatMessage>(_chatHistoryBox);
    await box.clear();
  }

  // ─── Local File Cache ──────────────────────────────────────────────

  /// Cache a file item locally.
  Future<void> cacheFileItem(FileItem file) async {
    final box = _getBox<FileItem>(_filesBox);
    await box.put(file.id, file);
  }

  /// Get a cached file item.
  Future<FileItem?> getCachedFileItem(String id) async {
    final box = _getBox<FileItem>(_filesBox);
    return box.get(id);
  }

  /// Get all cached files for a project.
  Future<List<FileItem>> getCachedFilesForProject(String projectId) async {
    final box = _getBox<FileItem>(_filesBox);
    return box.values.where((f) => f.id.startsWith(projectId)).toList();
  }

  // ─── Utility ───────────────────────────────────────────────────────

  /// Extract session ID from a composite key.
  String _getMessageSessionId(String compositeKey) {
    final parts = compositeKey.split('_');
    if (parts.length >= 2) {
      return parts.sublist(0, parts.length - 5).join('_'); // Heuristic.
    }
    return compositeKey;
  }

  /// Export all data as a JSON-compatible map (for backup).
  Future<Map<String, dynamic>> exportAllData() async {
    final data = <String, dynamic>{};

    final projectsBox = _getBox<Project>(_projectsBox);
    data['projects'] = projectsBox.values.map((p) => {'id': p.id, 'name': p.name}).toList();

    final snippetsBox = _getBox<CodeSnippet>(_snippetsBox);
    data['snippets'] = snippetsBox.values.length;

    final configsBox = _getBox<ApiConfig>(_apiConfigsBox);
    data['apiConfigs'] = configsBox.values.length;

    final settingsBox = _getBox<dynamic>(_settingsBox);
    data['settings'] = settingsBox.keys.length;

    return data;
  }

  /// Clear all data (factory reset).
  Future<void> clearAllData() async {
    for (final entry in _boxes.entries) {
      await (entry.value as Box).clear();
    }
    debugPrint('[StorageService] Cleared all data');
  }

  /// Close all boxes and release resources.
  Future<void> dispose() async {
    for (final box in _boxes.values) {
      if (box.isOpen) {
        await box.close();
      }
    }
    _boxes.clear();
    _initialized = false;
    debugPrint('[StorageService] Disposed');
  }
}
