#!/usr/bin/env python3
"""Command-agent adapter for `/mc 写开发日志` -> Lark Docx reply experiments.

Default mode is dry-run and performs no Lark write.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any, Optional


def _now_label() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _compact(value: str, limit: int = 240) -> str:
    text = value.strip().replace("\n", " ")
    if len(text) <= limit:
        return text
    return f"{text[:limit]}..."


def _build_markdown(prompt: str) -> tuple[str, str]:
    stamp = _now_label()
    title = os.getenv("MOBILECODE_LARK_DEVLOG_TITLE", f"MobileCode 开发日志 {stamp[:10]}")
    body = f"""# {title}

Generated by MobileCode Lark relay.

## Trigger

{prompt.strip() or "/mc 写开发日志"}

## Summary

- Relay received an IM event from Lark.
- MobileCode agent prepared a development log document.
- This record is intended to be written to Lark Docx after explicit confirmation.

## Evidence

- generated_at: `{stamp}`
- source: `tools/lark_relay/agent_command_dev_log_docx.py`
- mode: `{os.getenv("MOBILECODE_LARK_DEVLOG_MODE", "dry-run")}`
"""
    return title, body


def _find_url_or_token(value: Any) -> Optional[str]:
    if isinstance(value, dict):
        for key, item in value.items():
            lower = str(key).lower()
            if any(marker in lower for marker in ("url", "link", "token", "document_id", "documentid")):
                if isinstance(item, (str, int)) and str(item).strip():
                    return str(item).strip()
            nested = _find_url_or_token(item)
            if nested:
                return nested
    if isinstance(value, list):
        for item in value:
            nested = _find_url_or_token(item)
            if nested:
                return nested
    return None


def _base_meta(title: str, mode: str) -> dict[str, Any]:
    return {
        "chain_stage": "event_to_docx_to_reply",
        "next_action": "reply_dry_run_with_docx_preview",
        "lark_docx": {
            "status": "dry_run",
            "title": title,
            "document_url": "",
            "token_mode": os.getenv("MOBILECODE_LARK_DEVLOG_AS", "user").strip() or "user",
            "mode": mode,
            "failure_kind": "none",
        },
    }


def _create_docx(title: str, markdown: str) -> tuple[int, str, dict[str, Any]]:
    mode = os.getenv("MOBILECODE_LARK_DEVLOG_MODE", "dry-run").strip().lower()
    live_allowed = os.getenv("MOBILECODE_LARK_DEVLOG_ALLOW_LIVE") == "1"
    identity = os.getenv("MOBILECODE_LARK_DEVLOG_AS", "user").strip() or "user"
    folder_token = os.getenv("MOBILECODE_LARK_DEVLOG_FOLDER_TOKEN", "").strip()
    meta = _base_meta(title, mode)
    meta["lark_docx"]["token_mode"] = identity

    if mode != "live":
        return (
            0,
            (
                "Dev log Docx dry-run ready. "
                f"Title: {title}. "
                "Next: set MOBILECODE_LARK_DEVLOG_MODE=live and "
                "MOBILECODE_LARK_DEVLOG_ALLOW_LIVE=1 after confirming the target folder."
            ),
            meta,
        )
    if not live_allowed:
        meta["next_action"] = "confirm_live_docx_create_before_retry"
        meta["lark_docx"]["status"] = "blocked"
        meta["lark_docx"]["failure_kind"] = "live_write_not_confirmed"
        return (
            2,
            "Live Docx create blocked: set MOBILECODE_LARK_DEVLOG_ALLOW_LIVE=1 explicitly.",
            meta,
        )

    command = [
        "lark-cli",
        "docs",
        "+create",
        "--api-version",
        "v2",
        "--doc-format",
        "markdown",
        "--title",
        title,
        "--content",
        markdown,
        "--as",
        identity,
        "--format",
        "json",
    ]
    if folder_token:
        command.extend(["--folder-token", folder_token])

    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    output = (result.stdout or result.stderr or "").strip()
    if result.returncode != 0:
        meta["next_action"] = "inspect_docx_create_scope_folder_or_cli_output"
        meta["lark_docx"]["status"] = "failed"
        meta["lark_docx"]["failure_kind"] = "docx_create_failed"
        meta["lark_docx"]["error_preview"] = _compact(output)
        return result.returncode, f"Dev log Docx create failed: {_compact(output)}", meta

    try:
        decoded = json.loads(output)
    except json.JSONDecodeError:
        decoded = {"raw": output}
    link = _find_url_or_token(decoded)
    meta["next_action"] = "reply_sent_with_docx_link"
    meta["lark_docx"]["status"] = "created"
    if link:
        meta["lark_docx"]["document_url"] = link
        return 0, f"Development log Docx created: {link}", meta
    meta["lark_docx"]["response_preview"] = _compact(output)
    return 0, f"Development log Docx created. Response: {_compact(output)}", meta


def main() -> int:
    prompt = sys.stdin.read().strip()
    title, markdown = _build_markdown(prompt)
    code, reply, meta = _create_docx(title, markdown)
    print(reply)
    print(f"MOBILECODE_RELAY_META_JSON={json.dumps(meta, ensure_ascii=False)}", file=sys.stderr)
    return code


if __name__ == "__main__":
    raise SystemExit(main())
