#!/usr/bin/env python3
"""Minimal Lark relay dry-run skeleton.

Implements mock event -> queue -> agent stub -> IM dry-run send.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import deque
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Deque, Optional
from uuid import uuid4


DEFAULT_TOOL = "lark_relay.mock"
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent / "evidence"


@dataclass
class MockEvent:
    """A small in-memory relay event."""

    event_id: str
    request_id: str
    chat_id: str
    sender_id: str
    message_text: str
    received_at: str

    def to_dict(self) -> dict:
        return asdict(self)


class InMemoryEventQueue:
    """Simple queue used by the mock relay runner."""

    def __init__(self) -> None:
        self._items: Deque[MockEvent] = deque()

    def enqueue(self, event: MockEvent) -> None:
        self._items.append(event)

    def dequeue(self) -> Optional[MockEvent]:
        if not self._items:
            return None
        return self._items.popleft()

    @property
    def size(self) -> int:
        return len(self._items)

    @property
    def is_empty(self) -> bool:
        return not self._items


def _now_iso8601() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _new_request_id() -> str:
    return f"req-{uuid4()}"


def _new_event_id() -> str:
    return f"evt-{uuid4()}"


def _new_dry_run_id() -> str:
    return f"dry-run-{uuid4()}"


def _load_event_payload(event_json: Optional[str], event_file: Optional[str]) -> Optional[dict]:
    if event_json:
        try:
            return json.loads(event_json)
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid --event-json: {exc}") from exc

    if event_file:
        path = Path(event_file)
        if not path.exists():
            raise FileNotFoundError(f"--event-file not found: {path}")
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid JSON in --event-file: {path}: {exc}") from exc

    return None


def _build_event(args: argparse.Namespace) -> MockEvent:
    payload = _load_event_payload(args.event_json, args.event_file) or {}
    message_text = payload.get("message_text", args.message or "").strip()
    if not message_text:
        message_text = args.message or "Hello, this is a mock Lark DM event."

    event_id = payload.get("event_id") or args.event_id or _new_event_id()
    request_id = payload.get("request_id") or args.request_id or _new_request_id()
    chat_id = payload.get("chat_id") or args.chat_id
    sender_id = payload.get("sender_id") or args.sender_id

    # allow alternate wire schema: {"message": {"text": "..."}}
    if not payload.get("message_text") and isinstance(payload.get("message"), dict):
        nested_text = payload["message"].get("text")
        if isinstance(nested_text, str) and nested_text.strip():
            message_text = nested_text.strip()

    return MockEvent(
        event_id=str(event_id),
        request_id=str(request_id),
        chat_id=str(chat_id),
        sender_id=str(sender_id),
        message_text=message_text,
        received_at=_now_iso8601(),
    )


def _agent_stub(message_text: str, failure_mode: str) -> tuple[str, str]:
    if not message_text.strip():
        return "empty_message", "reply to empty messages requires input text"
    if failure_mode == "agent_error":
        return "agent_unavailable", "Mock agent temporarily unavailable"

    normalized = message_text.strip()
    return "none", f"Mock reply: 已收到你的消息 “{normalized}”。"


def _im_send_adapter(reply_text: str, failure_mode: str) -> tuple[str, str]:
    if failure_mode == "send_blocked":
        return "im_send_blocked", "IM adapter blocked (dry-run mode)."
    if not reply_text:
        return "no_reply_payload", "Nothing generated by agent."
    return "none", f"Dry-run send ok: {reply_text}"


def _build_next_action(failure_kind: str) -> str:
    if failure_kind == "none":
        return "mock_reply_sent"
    if failure_kind == "empty_message":
        return "rerun_with_non_empty_message"
    if failure_kind == "agent_unavailable":
        return "retry_agent_or_switch_stub"
    if failure_kind == "im_send_blocked":
        return "check_im_dry_run_adapter"
    if failure_kind == "no_reply_payload":
        return "run_agent_stub_again"
    return "investigate_failure_kind"


def run_relay_once(event: MockEvent, tool: str, simulate_failure: str) -> dict:
    queue = InMemoryEventQueue()
    queue.enqueue(event)

    loop_state = {
        "queue_size_before": queue.size,
        "events_processed": 0,
        "events": [],
    }
    queue_state = []
    failure_kind = "none"
    next_action = "mock_reply_sent"
    reply_text = ""
    request_id = event.request_id

    while not queue.is_empty:
        current = queue.dequeue()
        if current is None:
            break
        loop_state["events_processed"] += 1

        agent_failure, agent_reply = _agent_stub(current.message_text, simulate_failure)
        if agent_failure != "none":
            failure_kind = agent_failure
            next_action = _build_next_action(failure_kind)
            reply_text = ""
        else:
            reply_text = agent_reply
            send_failure, send_message = _im_send_adapter(reply_text, simulate_failure)
            if send_failure != "none":
                failure_kind = send_failure
                next_action = _build_next_action(failure_kind)
            else:
                failure_kind = "none"
                next_action = "mock_reply_sent"

        queue_state.append(
            {
                "event_id": current.event_id,
                "request_id": current.request_id,
                "message_text": current.message_text,
                "agent_reply_text": reply_text,
                "queue_depth_before": loop_state["queue_size_before"],
                "queue_depth_after": queue.size,
            }
        )
        loop_state["queue_size_before"] = queue.size

        # On failure, stop processing further events to preserve deterministic ordering.
        if failure_kind != "none":
            break

    evidence = {
        "tool": tool,
        "event_id": event.event_id,
        "request_id": request_id,
        "dry_run_id": _new_dry_run_id(),
        "failure_kind": failure_kind,
        "next_action": next_action,
        "message_text": event.message_text,
        "reply_text": reply_text,
        "timestamp": _now_iso8601(),
        "queue": {
            "final_size": queue.size,
            "runs": queue_state,
        },
        "result_summary": {
            "events_processed": loop_state["events_processed"],
            "events_accepted": 1,
        },
    }
    return evidence


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run a minimal Lark relay mock loop and write dry-run evidence JSON."
    )
    parser.add_argument(
        "--message",
        help="Message text for the generated mock event.",
    )
    parser.add_argument(
        "--request-id",
        help="Optional request id for the event.",
    )
    parser.add_argument(
        "--event-id",
        help="Optional event id for the generated mock event.",
    )
    parser.add_argument(
        "--chat-id",
        default="chat-demo-01",
        help="Chat id to include in the mock event.",
    )
    parser.add_argument(
        "--sender-id",
        default="user-demo-01",
        help="Sender id to include in the mock event.",
    )
    parser.add_argument(
        "--event-json",
        help="Inline JSON string for a mock event.",
    )
    parser.add_argument(
        "--event-file",
        help="JSON file path for a mock event payload.",
    )
    parser.add_argument(
        "--simulate-failure",
        choices=["none", "agent_error", "send_blocked"],
        default="none",
        help="Injected failure mode for mock dry-run.",
    )
    parser.add_argument(
        "--tool",
        default=DEFAULT_TOOL,
        help="Tool name used in evidence output.",
    )
    parser.add_argument(
        "--output",
        help=(
            "Output path for evidence JSON. "
            "Defaults to tools/lark_relay/evidence/<dry_run_id>.json"
        ),
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    if args.event_json and args.event_file:
        parser.error("use either --event-json or --event-file, not both")

    try:
        event = _build_event(args)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    evidence = run_relay_once(event, args.tool, args.simulate_failure)

    output = Path(args.output) if args.output else DEFAULT_OUTPUT_DIR / f"{evidence['dry_run_id']}.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(evidence, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"dry-run evidence written: {output}")
    print(json.dumps(evidence, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
